/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rouart Antoine
 */
public class cadenas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(cadenas.class.getName());

    /**
     * Creates new form cadenas
     */
    public cadenas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        texte_intro = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentative = new javax.swing.JLabel();
        bouton_tester = new javax.swing.JButton();
        bouton_recommencer = new javax.swing.JButton();
        texte_nb_chiffre_exacts = new javax.swing.JLabel();
        texte_val_nb_chiffre_exacts = new javax.swing.JLabel();
        texte_nb_chiffre_trop_haut = new javax.swing.JLabel();
        texte_val_nombre_chiffre_trop_haut = new javax.swing.JLabel();
        texte_nb_chiffre_trop_bas = new javax.swing.JLabel();
        texte_val_nb_chiffre_trop_bas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chiffre_1.setText("jButton1");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 96, -1, -1));

        up_chiffre_2.setText("jButton1");
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 96, -1, -1));

        up_chiffre_3.setText("jButton1");
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 96, -1, -1));

        up_chiffre_4.setText("jButton1");
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 96, -1, -1));

        down_chiffre_1.setText("jButton1");
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 197, -1, -1));

        down_chiffre_2.setText("jButton1");
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 197, -1, -1));

        down_chiffre_3.setText("jButton1");
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 197, -1, -1));

        down_chiffre_4.setText("jButton1");
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 197, -1, -1));

        texte_chiffre_1.setText("jLabel1");
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 125, 75, 66));

        texte_chiffre_2.setText("jLabel1");
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 125, 75, 66));

        texte_chiffre_3.setText("jLabel1");
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 125, 75, 66));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 125, 75, 66));

        texte_intro.setText("Trouve le bon code en moins de 5 tentatives!");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 24, 318, 33));

        texte_score.setText("Score");
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 125, 102, 41));

        texte_tentative.setText("Tentatives:");
        getContentPane().add(texte_tentative, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 99, -1, -1));

        bouton_tester.setText("jButton1");
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 63, -1, -1));

        bouton_recommencer.setText("jButton1");
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        texte_nb_chiffre_exacts.setText("Nombre de chiffre exact:");
        getContentPane().add(texte_nb_chiffre_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 238, 143, 24));

        texte_val_nb_chiffre_exacts.setText("jLabel3");
        getContentPane().add(texte_val_nb_chiffre_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 242, -1, -1));

        texte_nb_chiffre_trop_haut.setText("Nombre de chiffre trop haut :");
        getContentPane().add(texte_nb_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 268, -1, -1));

        texte_val_nombre_chiffre_trop_haut.setText("jLabel2");
        getContentPane().add(texte_val_nombre_chiffre_trop_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 268, -1, -1));

        texte_nb_chiffre_trop_bas.setText("Nombre de chiffre trop bas :");
        getContentPane().add(texte_nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 290, -1, -1));

        texte_val_nb_chiffre_trop_bas.setText("jLabel3");
        getContentPane().add(texte_val_nb_chiffre_trop_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_nb_chiffre_exacts;
    private javax.swing.JLabel texte_nb_chiffre_trop_bas;
    private javax.swing.JLabel texte_nb_chiffre_trop_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentative;
    private javax.swing.JLabel texte_val_nb_chiffre_exacts;
    private javax.swing.JLabel texte_val_nb_chiffre_trop_bas;
    private javax.swing.JLabel texte_val_nombre_chiffre_trop_haut;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
