
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rouart Antoine
 */

public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();        
        initialiserQuestions();     
        afficherQuestionCourante();
        }
    int Score=0;
    private ArrayList<Question> questions = new ArrayList<>();
    private int indexQuestionCourante = 0; 
    private void initialiserQuestions() {     
        questions.add(new Question(
            "Quel est le plus grand océan du monde ?",
            "Atlantique",
            "Indien",
            "Arctique",
            "Pacifique",
            4
        ));

        questions.add(new Question(
            "Quelle planète est la plus proche du Soleil ?",
            "Venus",
            "Terre",
            "Mercure",
            "Mars",
            3
        ));

        questions.add(new Question(
            "Quelle est la capitale de l'Australie ?",
            "Sydney",
            "Melbourne",
            "Canberra",
            "Brisbane",
            3
        ));

        questions.add(new Question(
            "Combien de continents compte la Terre ?",
            "5",
            "6",
            "7",
            "8",
            3
        ));

        questions.add(new Question(
            "Quel est le gaz le plus présent dans l’atmosphère terrestre ?",
            "Oxygène",
            "Azote",
            "CO₂",
            "Hélium",
            2
        ));
    }

private void afficherQuestionCourante(){    
    indexQuestionCourante++;    
    Question q = questions.get(indexQuestionCourante);
    lblQuestion.setText(q.getIntitule());
    btnRep1.setText(q.getProposition1());
    btnRep2.setText(q.getProposition2());
    btnRep3.setText(q.getProposition3());
    btnRep4.setText(q.getProposition4());
    btnRep1.setEnabled(true);
    btnRep2.setEnabled(true);
    btnRep3.setEnabled(true);
    btnRep4.setEnabled(true);
    Fin.setVisible(false);
    Feedback.setVisible(false);
   }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        Feedback = new javax.swing.JLabel();
        labelScore = new javax.swing.JLabel();
        Question_suiv = new javax.swing.JButton();
        Fin = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(122, 66, 200));
        lblQuestion.setText("      Intitulé");

        btnRep1.setText("Bouton 1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("Bouton 2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("Bouton 3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("Bouton 4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        Feedback.setText("Feedback");

        labelScore.setText("Score: ");

        Question_suiv.setText("Question Suivante");
        Question_suiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question_suivActionPerformed(evt);
            }
        });

        Fin.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Fin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                        .addComponent(Question_suiv)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(Feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question_suiv)
                    .addComponent(labelScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Feedback, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
    int Choix=1;
    int indexCourant = indexQuestionCourante;    
    Question q = questions.get(indexCourant);    
    int Reponse = q.getIndexBonneReponse();
    if (Choix == Reponse) {
    Score++;           
    Feedback.setText("Bonne réponse!");    
    Feedback.setVisible(true);
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);  
    }   
    else{
    Feedback.setVisible(true);
    Feedback.setText("Mauvaise réponse, t'es nul!"); 
    Feedback.setVisible(true);
    }
    labelScore.setText("Score :"+Score);
    btnRep1.setEnabled(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void Question_suivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question_suivActionPerformed
    int indexCourant = indexQuestionCourante;    
    int Taille=questions.size();  
    Taille=Taille-1;
    if (indexCourant < Taille){
        afficherQuestionCourante();
    }
    else{
        Fin.setVisible(true);
        Fin.setText("Quiz terminé. Score : " + Score + " / " + Taille);
        Question_suiv.setEnabled(false); 
    }
    }//GEN-LAST:event_Question_suivActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
    int Choix=3;
    int indexCourant = indexQuestionCourante;
    Question q = questions.get(indexCourant);     
    int Reponse = q.getIndexBonneReponse();
    if (Choix == Reponse) {
    Score++;   
    Feedback.setText("Bonne réponse!");   
    Feedback.setVisible(true);
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false);    
    }   
    else{
    Feedback.setText("Mauvaise réponse, t'es nul!"); 
    Feedback.setVisible(true);
    }
    labelScore.setText("Score :"+Score);
    btnRep3.setEnabled(false);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
    int Choix=2;
    int indexCourant = indexQuestionCourante;
    Question q = questions.get(indexCourant);      
    int Reponse = q.getIndexBonneReponse();
    if (Choix == Reponse) {
    Score++;   
    Feedback.setText("Bonne réponse!")   ;    
    Feedback.setVisible(true);
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false); 
    }   
    else{
    Feedback.setText("Mauvaise réponse, t'es nul!"); 
    Feedback.setVisible(true);
    }
    labelScore.setText("Score :"+Score);
    btnRep2.setEnabled(false);
    
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
    int Choix=4;
    int indexCourant = indexQuestionCourante;
    Question q = questions.get(indexCourant);     
    int Reponse = q.getIndexBonneReponse();
    if (Choix == Reponse) {
    Score++;   
    Feedback.setText("Bonne réponse!")   ;  
    Feedback.setVisible(true);
    btnRep1.setEnabled(false);
    btnRep2.setEnabled(false);
    btnRep3.setEnabled(false);
    btnRep4.setEnabled(false); 
    }   
    else{
    Feedback.setText("Mauvaise réponse, t'es nul!"); 
    Feedback.setVisible(true);
    }
    labelScore.setText("Score :"+Score);
    btnRep4.setEnabled(false);  
    }//GEN-LAST:event_btnRep4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Feedback;
    private javax.swing.JLabel Fin;
    private javax.swing.JButton Question_suiv;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelScore;
    private javax.swing.JLabel lblQuestion;
    // End of variables declaration//GEN-END:variables
}
